apiVersion: v1
kind: Service
metadata:
  name: lembretes-service
spec:
  #Ip externo, acessível fora do cluster
  type: NodePort
  selector:
    #todo Pode que tiver essa tag
    #fará parte desse serviço
    app: lembretes
  ports:
  - name: lembretes
    protocol: TCP
    # o nó só recebe requisições nessa porta
    port: 4000
    # e direciona para essa porta do Pod
